// ==========================================
// shared/sounds.js
// Retro Audio Engine for Worm Game
//
// Created by: Gemini
// Note: This shared asset is provided as part of the testing framework.
// It was NOT generated by the local LLMs (Gemma, Qwen, etc.) being
// evaluated in this competence development arena.
// ==========================================

const audioCtx = new (window.AudioContext || window.webkitAudioContext)();

// Browsers suspend audio until the user interacts with the page.
// This function ensures the audio engine wakes up on the first keypress.
function unlockAudio() {
    if (audioCtx.state === 'suspended') {
        audioCtx.resume();
    }
}
document.addEventListener('keydown', unlockAudio, { once: true });
document.addEventListener('click', unlockAudio, { once: true });

/**
 * Core function to generate a retro sound wave
 * @param {number} startFreq - Starting pitch in Hz
 * @param {number} duration - How long the sound lasts in seconds
 * @param {string} type - Waveform: 'square', 'sawtooth', or 'triangle'
 * @param {number} endFreq - (Optional) End pitch for sliding sounds
 */
function playRetroSound(startFreq, duration, type = 'square', endFreq = null) {
    unlockAudio();

    const oscillator = audioCtx.createOscillator();
    const gainNode = audioCtx.createGain();

    oscillator.type = type;

    // Set starting pitch
    oscillator.frequency.setValueAtTime(startFreq, audioCtx.currentTime);

    // If an end frequency is provided, slide the pitch (creates classic arcade 'pew' or 'drop' sounds)
    if (endFreq) {
        oscillator.frequency.exponentialRampToValueAtTime(endFreq, audioCtx.currentTime + duration);
    }

    // Set volume envelope: start at 10% volume, fade out to prevent speaker clicking
    gainNode.gain.setValueAtTime(0.1, audioCtx.currentTime);
    gainNode.gain.exponentialRampToValueAtTime(0.001, audioCtx.currentTime + duration);

    // Connect and play
    oscillator.connect(gainNode);
    gainNode.connect(audioCtx.destination);

    oscillator.start();
    oscillator.stop(audioCtx.currentTime + duration);
}

// ==========================================
// GLOBAL GAME SOUND API
// ==========================================

// Expose these specific functions globally so the AI can call them easily

window.playMoveSound = function() {
    // Very short, low 'tick' sound
    playRetroSound(150, 0.05, 'triangle');
};

window.playEatSound = function() {
    // Classic coin/pickup sound: rapid pitch jump upwards
    playRetroSound(400, 0.1, 'square', 1200);
};

window.playGameOverSound = function() {
    // Harsh, descending buzz
    playRetroSound(300, 0.6, 'sawtooth', 50);
};